stages:
  - build
  - deploy
  - push2github

build_blogs:
  image: dockerhub.bmi:5000/sphinx-rtd
  stage: build
  only:
    - master
  artifacts:
    paths:
      - build
  script:
    - make html

deploy_blogs:
  image: dockerhub.bmi:5000/ubuntu16-expect
  stage: deploy
  only:
    - master
  when: on_success
  dependencies:
    - build_blogs
  script:
    - ( test ! -z "$machineURL" -a ! -z "$machinePWD" ) || ( echo "upload2machine failure [error=machineURL or machinePWD undefined]" && exit 10 )
    - ./for-upload2machine.sh $machineURL $machinePWD

push2github_blogs:
  image: dockerhub.bmi:5000/ubuntu16-expect-git
  stage: push2github
  only:
    - master
  when: on_success
  script:
    - ( test ! -z "$githubURL" -a ! -z "$githubUser" -a ! -z "$githubPWD" ) || ( echo "push2github failure [error=githubURL or githubUser or githubPWD undefined]" && exit 10 )
    - git remote remove github || true
    - ./for-push2github.sh $githubURL $githubUser $githubPWD
    - git remote remove github || true
  retry: 2